name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-client:
    if: contains(github.event.commits[0].modified, 'apps/client')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: pnpm install
      - run: pnpm --filter client build
      - run: pm2 restart client

  deploy-db:
    if: contains(github.event.commits[0].modified, 'apps/db')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: pnpm install
      - run: pnpm --filter db build
      - run: pm2 restart db

  deploy-server:
    if: contains(github.event.commits[0].modified, 'apps/server')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: pnpm install
      - run: pnpm --filter server build
      - run: pm2 restart server
